### ISSUE TITLE
Build failure of 0.5 with `rustfft-complex` feature enabled.

### ISSUE THREAD

**Issue by tkaitchuck** [phip1611/spectrum-analyzer#30]
Building 0.5 fails with the `rustfft-complex` feature. 
I am attempting to enable this feature because the default feature set panics at runtime when given more than 4096 samples.

**Comment by tkaitchuck** [comment]
>    Compiling spectrum-analyzer v0.5.0
error[E0659]: `Complex32` is ambiguous (glob import vs glob import in the same module)
  --> /home/tom/.cargo/registry/src/github.com-1ecc6299db9ec823/spectrum-analyzer-0.5.0/src/lib.rs:40:18
   |
40 | use crate::fft::{Complex32, Fft, FftImpl};
   |                  ^^^^^^^^^ ambiguous name
   |
note: `Complex32` could refer to the type alias imported here
  --> /home/tom/.cargo/registry/src/github.com-1ecc6299db9ec823/spectrum-analyzer-0.5.0/src/fft/mod.rs:53:9
   |
53 | pub use microfft_real::*;
   |         ^^^^^^^^^^^^^^^^
   = help: consider adding an explicit import of `Complex32` to disambiguate
note: `Complex32` could also refer to the type alias imported here
  --> /home/tom/.cargo/registry/src/github.com-1ecc6299db9ec823/spectrum-analyzer-0.5.0/src/fft/mod.rs:58:9
   |
58 | pub use rustfft_complex::*;
   |         ^^^^^^^^^^^^^^^^^^
   = help: consider adding an explicit import of `Complex32` to disambiguate

> error[E0659]: `FftImpl` is ambiguous (glob import vs glob import in the same module)
  --> /home/tom/.cargo/registry/src/github.com-1ecc6299db9ec823/spectrum-analyzer-0.5.0/src/lib.rs:40:34
   |
40 | use crate::fft::{Complex32, Fft, FftImpl};
   |                                  ^^^^^^^ ambiguous name
   |
note: `FftImpl` could refer to the struct imported here
  --> /home/tom/.cargo/registry/src/github.com-1ecc6299db9ec823/spectrum-analyzer-0.5.0/src/fft/mod.rs:53:9
   |
53 | pub use microfft_real::*;
   |         ^^^^^^^^^^^^^^^^
   = help: consider adding an explicit import of `FftImpl` to disambiguate
note: `FftImpl` could also refer to the struct imported here
  --> /home/tom/.cargo/registry/src/github.com-1ecc6299db9ec823/spectrum-analyzer-0.5.0/src/fft/mod.rs:58:9
   |
58 | pub use rustfft_complex::*;
   |         ^^^^^^^^^^^^^^^^^^
   = help: consider adding an explicit import of `FftImpl` to disambiguate

> error[E0659]: `FftImpl` is ambiguous (glob import vs glob import in the same module)
  --> /home/tom/.cargo/registry/src/github.com-1ecc6299db9ec823/spectrum-analyzer-0.5.0/src/lib.rs:40:34
   |
40 | use crate::fft::{Complex32, Fft, FftImpl};
   |                                  ^^^^^^^ ambiguous name
   |
note: `FftImpl` could refer to the unit struct imported here
  --> /home/tom/.cargo/registry/src/github.com-1ecc6299db9ec823/spectrum-analyzer-0.5.0/src/fft/mod.rs:53:9
   |
53 | pub use microfft_real::*;
   |         ^^^^^^^^^^^^^^^^
   = help: consider adding an explicit import of `FftImpl` to disambiguate
note: `FftImpl` could also refer to the unit struct imported here
  --> /home/tom/.cargo/registry/src/github.com-1ecc6299db9ec823/spectrum-analyzer-0.5.0/src/fft/mod.rs:58:9
   |
58 | pub use rustfft_complex::*;
   |         ^^^^^^^^^^^^^^^^^^
   = help: consider adding an explicit import of `FftImpl` to disambiguate

> error[E0659]: `FftImpl` is ambiguous (glob import vs glob import in the same module)
   --> /home/tom/.cargo/registry/src/github.com-1ecc6299db9ec823/spectrum-analyzer-0.5.0/src/lib.rs:123:18
    |
123 |     let buffer = FftImpl::fft_apply(samples);
    |                  ^^^^^^^ ambiguous name
    |
note: `FftImpl` could refer to the struct imported here
   --> /home/tom/.cargo/registry/src/github.com-1ecc6299db9ec823/spectrum-analyzer-0.5.0/src/fft/mod.rs:53:9
    |
53  | pub use microfft_real::*;
    |         ^^^^^^^^^^^^^^^^
    = help: consider adding an explicit import of `FftImpl` to disambiguate
note: `FftImpl` could also refer to the struct imported here
   --> /home/tom/.cargo/registry/src/github.com-1ecc6299db9ec823/spectrum-analyzer-0.5.0/src/fft/mod.rs:58:9
    |
58  | pub use rustfft_complex::*;
    |         ^^^^^^^^^^^^^^^^^^
    = help: consider adding an explicit import of `FftImpl` to disambiguate

> error[E0659]: `Complex32` is ambiguous (glob import vs glob import in the same module)
   --> /home/tom/.cargo/registry/src/github.com-1ecc6299db9ec823/spectrum-analyzer-0.5.0/src/lib.rs:163:19
    |
163 |     fft_result: &[Complex32],
    |                   ^^^^^^^^^ ambiguous name
    |
note: `Complex32` could refer to the type alias imported here
   --> /home/tom/.cargo/registry/src/github.com-1ecc6299db9ec823/spectrum-analyzer-0.5.0/src/fft/mod.rs:53:9
    |
53  | pub use microfft_real::*;
    |         ^^^^^^^^^^^^^^^^
    = help: consider adding an explicit import of `Complex32` to disambiguate
note: `Complex32` could also refer to the type alias imported here
   --> /home/tom/.cargo/registry/src/github.com-1ecc6299db9ec823/spectrum-analyzer-0.5.0/src/fft/mod.rs:58:9
    |
58  | pub use rustfft_complex::*;
    |         ^^^^^^^^^^^^^^^^^^
    = help: consider adding an explicit import of `Complex32` to disambiguate

> error[E0659]: `FftImpl` is ambiguous (glob import vs glob import in the same module)
   --> /home/tom/.cargo/registry/src/github.com-1ecc6299db9ec823/spectrum-analyzer-0.5.0/src/lib.rs:187:15
    |
187 |         .take(FftImpl::fft_relevant_res_samples_count(samples_len))
    |               ^^^^^^^ ambiguous name
    |
note: `FftImpl` could refer to the struct imported here
   --> /home/tom/.cargo/registry/src/github.com-1ecc6299db9ec823/spectrum-analyzer-0.5.0/src/fft/mod.rs:53:9
    |
53  | pub use microfft_real::*;
    |         ^^^^^^^^^^^^^^^^
    = help: consider adding an explicit import of `FftImpl` to disambiguate
note: `FftImpl` could also refer to the struct imported here
   --> /home/tom/.cargo/registry/src/github.com-1ecc6299db9ec823/spectrum-analyzer-0.5.0/src/fft/mod.rs:58:9
    |
58  | pub use rustfft_complex::*;
    |         ^^^^^^^^^^^^^^^^^^
    = help: consider adding an explicit import of `FftImpl` to disambiguate

> error[E0659]: `Complex32` is ambiguous (glob import vs glob import in the same module)
   --> /home/tom/.cargo/registry/src/github.com-1ecc6299db9ec823/spectrum-analyzer-0.5.0/src/lib.rs:288:31
    |
288 | fn complex_to_magnitude(val: &Complex32) -> f32 {
    |                               ^^^^^^^^^ ambiguous name
    |
note: `Complex32` could refer to the type alias imported here
   --> /home/tom/.cargo/registry/src/github.com-1ecc6299db9ec823/spectrum-analyzer-0.5.0/src/fft/mod.rs:53:9
    |
53  | pub use microfft_real::*;
    |         ^^^^^^^^^^^^^^^^
    = help: consider adding an explicit import of `Complex32` to disambiguate
note: `Complex32` could also refer to the type alias imported here
   --> /home/tom/.cargo/registry/src/github.com-1ecc6299db9ec823/spectrum-analyzer-0.5.0/src/fft/mod.rs:58:9
    |
58  | pub use rustfft_complex::*;
    |         ^^^^^^^^^^^^^^^^^^
    = help: consider adding an explicit import of `Complex32` to disambiguate

**Comment by phip1611** [comment]
Hi @tkaitchuck
Hm, I'm wondering why this is not reported by CI 🤔
I'm going to fix this in the next 48 hours, thanks for reporting it!

**Comment by phip1611** [comment]
Ahh, you must exclude the default feature! This crate compiles only iff there is exactly one feature provided. 

```toml
[dependencies]
specturm-analyzer = { feature = "rustfft-complex", no-default-features = true }
```

I'll add it to the readme.

PS: `microfft` will hopefully soon also work with FFT sizes bigger than 4096, see https://gitlab.com/ra_kete/microfft-rs/-/issues/8
