### ISSUE TITLE
when sample data is all 0.0  thread 'main' panicked at 'min must be <= max  min:NaN max: NaN', src/spectrum.rs:469:9

### ISSUE THREAD

**Issue by wasabia** [phip1611/spectrum-analyzer#33]
if our samples len is short  only 2 
samples data is [0.0, 0.0]

when run not release

```
thread 'main' panicked at 'min must be <= max  min:NaN max: NaN', src/spectrum.rs:469:9
```

**Comment by phip1611** [comment]
Hi @wasabia 
can you please give some more details. With what other parameters are you invoking the lib?

**Comment by wasabia** [comment]
Hi @phip1611 
i just run the example

this error happen

Change
```
to_spectrum_and_plot(
        &samples[0..4096],
        sampling_rate,
        "example__mp3-samples__bass_drum__spectrum",
        FrequencyLimit::Max(5000.0),
    )
```

To

to_spectrum_and_plot(
        &samples[0..128],
        sampling_rate,
        "example__mp3-samples__bass_drum__spectrum",
        FrequencyLimit::Max(5000.0),
    )
```

**Comment by phip1611** [comment]
Thanks for the feedback. I'll refactor the whole scaling functionality, make it simpler and less error-prone in the next release - <7 days until the fix will be live

**Comment by phip1611** [comment]
Fixed on my dev branch. Release in a few days

**Comment by phip1611** [comment]
Took a little bit longer .. release in a few hours to days now! @wasabia
