### ISSUE TITLE
Max is not defined correctly

### ISSUE THREAD

**Issue by Norlock** [phip1611/spectrum-analyzer#45]
I used your method but found out it doesn't correlate with what the documentation says it should be doing. 

It returns: 53.833008 as max,

But when printing the data: 
```
2.6916504 22.81816
5.383301 2.1004658
8.074951 8.704016
10.766602 3.4043686
13.458252 8.649045
16.149902 9.210494
18.841553 14.937911
21.533203 5.1524887
24.224854 20.706167
26.916504 8.359295
29.608154 3.7514696
32.299805 15.109907
34.991455 86.791145
37.683105 52.140736
40.374756 24.108875
43.066406 11.070151
45.758057 10.569871
48.449707 6.1969466
51.141357 16.722788
53.833008 8.93011 
```
The 34.9x should be the max? 

Steps to reproduce:
* clone my repository https://github.com/norlock/sparticles branch input. commit: 17c1886a6072de2a8b54ee6140b6fcd6597cc381
* Select some audio input like a  microphone. 
* https://www.szynalski.com/tone-generator/ play a tone, I used 36hz
* see output not corresponding with the printed results.

**Comment by phip1611** [comment]
Hi @Norlock,

first of all: thanks for using my library! Regarding your issue: Yikes, so are right absolutely right! There is a bug. I'm going to fix and publish it within the next 7 days.

**Comment by Norlock** [comment]
No problem I'm using RustFFT now by it self, since I just want the dominant frequency. Just wanted to let you know, so don't feel rushed

**Comment by phip1611** [comment]
Hm. I added a unit test and it tells that everything works as expected:

<details>

```rust
#[test]
    fn test_max() {
        let maximum: (Frequency, FrequencyValue) = (34.991455.into(), 86.791145.into());
        let spectrum: Vec<(Frequency, FrequencyValue)> = vec![
            (2.6916504.into(), 22.81816.into()),
            (5.383301.into(), 2.1004658.into()),
            (8.074951.into(), 8.704016.into()),
            (10.766602.into(), 3.4043686.into()),
            (13.458252.into(), 8.649045.into()),
            (16.149902.into(), 9.210494.into()),
            (18.841553.into(), 14.937911.into()),
            (21.533203.into(), 5.1524887.into()),
            (24.224854.into(), 20.706167.into()),
            (26.916504.into(), 8.359295.into()),
            (29.608154.into(), 3.7514696.into()),
            (32.299805.into(), 15.109907.into()),
            maximum,
            (37.683105.into(), 52.140736.into()),
            (40.374756.into(), 24.108875.into()),
            (43.066406.into(), 11.070151.into()),
            (45.758057.into(), 10.569871.into()),
            (48.449707.into(), 6.1969466.into()),
            (51.141357.into(), 16.722788.into()),
            (53.833008.into(), 8.93011.into()),
        ];

        let spectrum_len = spectrum.len() as u32;
        let spectrum = FrequencySpectrum::new(spectrum, 44100.0, spectrum_len);

        assert_eq!(
            spectrum.max(),
            maximum,
            "Should return the maximum frequency value!"
        )
    }
```

</details>


Now I'm confused..

**Comment by phip1611** [comment]
Hm. I ran your example. I can't reproduce it :/ 

By the way: pretty cool project!

**Comment by Norlock** [comment]
Hmm i tried again now its working as well for, I think that for some reasons something wrong happened (maybe hardware or some sync issue but its working now). 

Thanks! Yeah busy with audio is pretty cool, somehow not that easy if its not a pure sine wave. Trying to make it work with my guitar but it starts becoming confused with the frequencies. Anyway keep up the work ;).
