### ISSUE TITLE
Support non-contiguous sample buffers

### ISSUE THREAD

**Issue by sowbug** [phip1611/spectrum-analyzer#55]
It would be very convenient if functions like `hann_window()` had an extra version that accepted at least two buffers rather than one. For the audio-processing domain that this crate targets, it seems that the source buffer would typically be a circular or ring buffer, which means that the logical buffer is usually two slices of the one physical buffer. As far as I can tell, to present the buffer for processing by this crate, one must memcpy into a temporary buffer, which defeats the ring buffer's main advantage vs a deque of never needing to move memory.

(For now I'm just passing in the ring buffer as if it were a regular contiguous chunk of memory, because the wrap point is mostly irrelevant for my application. I know approximately nothing about signal processing, so it's possible this is true for most or all use cases covered by this crate.)

**Comment by phip1611** [comment]
Hi @sowbug 
thanks for the interest in my library. I'll have a look into it.

**Comment by phip1611** [comment]
Hi, sorry for the late reply. I don't think that we can prevent the mem-copy from a cirucular buffer to a continuous slice in memory. The underlying FFT

https://github.com/phip1611/spectrum-analyzer/blob/main/src/fft.rs#L73

only works with a continuous slice in memory. 

If `hann_window` and other functions work on non-continous buffers, you just "copy to continuous"-problem to the next step.


Feel free to re-open if I'm missing something.

**Comment by sowbug** [comment]
Thanks for looking into it -- I appreciate it! I guess my next logical step
would be to ask the same of the microfft author, but I'm not sure it's
worth boiling the ocean for this small optimization.

**Comment by phip1611** [comment]
On which hardware platform are you working? Copying ~2048 samples in memory should be fairly quick even on the smallest available state-of-the-art embedded system. Correct me if I'm wrong.

**Comment by sowbug** [comment]
Agreed. Current targets are PC platforms on amd64 and arm64. Cortex M-class
could be a foreseeable target, but in that case I don't think we'd include
the feature that depends on FFT (a frequency-spectrum GUI widget). The
overall project is a digital-audio library that I'm also building into a
simple DAW.
