### ISSUE TITLE
Getting complex result

### ISSUE THREAD

**Issue by 4321ba** [phip1611/spectrum-analyzer#58]
Hi!
First of all, thank you very much for the library!
There is something I want to test which requires me to get the complex result of the fft calculation, however I cannot really find a way to get it, unless I dig into the library. Is there a way I missed, or do I need to modify the library for that?
Thanks a lot!

**Comment by phip1611** [comment]
Hey! This information is purposely lost to perform the necessary calculations. See https://github.com/phip1611/spectrum-analyzer/blob/f6858176ff2fc4c70e8e0ea08ad37cc5ea99c811/src/lib.rs#L311

I recommend to work directly with an FFT library that works with the FFT result in a way that you need. This is out of scope of this library

**Comment by 4321ba** [comment]
Hi, thank you for the quick response, and will look into working with rustfft/microfft!
